### ISSUE TITLE
Investigate PostgreSQL DB on AWS has required features

### ISSUE THREAD

**Issue by SKairinos** [ocadotechnology/codeforlife-workspace#133]
Investigate if GCP app can communicate with AWS DB.

Tasks to do:
- [ ] Adapt migrations to Postgres
- [ ] Create DB instance via Chancellor
- [ ] Set up pull mirroring on Gitlab
- [ ] Run migrations
- [ ] Fix existing contributor pipeline (may exist already)
- [ ] Deploy service pipeline
- [ ] Data transfer script

**Comment by SKairinos** [comment]
I have come to the following conclusions:

1. We don't need to worry about security settings. These are handled for us by the Chancellor team and we should make it their responsibility.

2. We currently have a max of 88GB and are using 72GB. We should upgrade to at least 100GB.

3. We are at 68% CPU utilisation with 4 vCPUs, 15GB RAM. This is sufficient for now. Should be <= 75%.

4. We are currently are over provisioned with IOPs. We have 2.64k/s but rarely exceed 450/s. Can reduce.

![Image](https://github.com/user-attachments/assets/9d51f3fb-e2c7-4ff7-8ea6-61e90f094c2c)

**Comment by faucomte97** [comment]
2. The "Max" of 88GB scales as needed.
