### ISSUE TITLE
Create DB instance via Chancellor

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-workspace#148]
Using Chancellor, create a PostgreSQL DB on AWS.

**Comment by SKairinos** [comment]
I have created a an RDS for PostgreSQL v16. Unfortunately, [PostgreSQL v17 is only on Amazon's preview environment](https://docs.aws.amazon.com/AmazonRDS/latest/PostgreSQLReleaseNotes/postgresql-versions.html#postgresql-version17) for now and, therefore, not available to Chancellor. When v17 becomes available, we should upgrade.
