### ISSUE TITLE
Set up pull mirroring on Gitlab

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-workspace#149]
On Ocado's Gitlab server, create a twin repo for each CFL repo currently on GitHub. Then, periodically pull all changes from GH into GL. Ideally, the pull mirroring will happen every min OR every 5 mins with the option to manually trigger a pull.

If it's possible we should do push mirroring instead of pull mirroring, where GH informs GL there's been a push.

**Comment by SKairinos** [comment]
Waiting for the [minimum pull interval](https://docs.gitlab.com/ee/administration/instance_limits.html#pull-mirroring-interval) to be lowered from 300 seconds to 30 seconds
