### ISSUE TITLE
new version email notification

### ISSUE THREAD

**Issue by SKairinos** [ocadotechnology/codeforlife-workspace#26]
Send a notification email to all contributors' email addresses when a new version of the contributor agreement is released. In addition, we need to add a section to the contributor agreement stating that's subject to edits, they will receive an email with a link to all new versions, and they may reach out to discontinue their contributions if they disagree with any new versions.

**Comment by lauracumming** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Code-for-Life-sprint-board-5dc58d4a85c6bd00010b8148/issues/ocadotechnology/codeforlife-workspace/26?planning-poker) with Zenhub @faucomte97 @SKairinos

**Comment by SKairinos** [comment]
getting legal approval
https://app.legalgateway.com.au/gateway/ltm/9abffb92-ed45-4c5a-ae79-82ac2f613bf9

**Comment by faucomte97** [comment]
make new task for button and email.
Update this task to include resigning request for all contributors
