### ISSUE TITLE
create new repo

### ISSUE THREAD

**Issue by SKairinos** [ocadotechnology/codeforlife-workspace#83]
Create the "codeforlife-contributor-backend" repo on GitHub. This should inherit the "codeforlife-template-backend" repo. 

- [ ] Rename the "codeforlife-service-template" repo to "codeforlife-template-backend".
- [ ] Update the BE template repo to contain the latest conventions in "codeforlife-portal-backend"
- [ ] Sync the BE template repo with the global config file.
- [ ] Create the new contributor repo and inherit the template.

**Comment by lauracumming** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Code-for-Life-sprint-board-5dc58d4a85c6bd00010b8148/issues/ocadotechnology/codeforlife-workspace/83?planning-poker) with Zenhub @faucomte97 @SKairinos
