### ISSUE TITLE
dev container (Ubuntu + python)

### ISSUE THREAD

**Issue by SKairinos** [ocadotechnology/codeforlife-workspace#9]
[see previous research](https://app.zenhub.com/workspaces/code-for-life-development--56f2afba6e54555c586f6db3/issues/gh/ocadotechnology/codeforlife-portal/2035)

create a dev container to be used as our local development environment. please ensure that our dev container is built in a Dockerfile. 

- [x] Use Ubuntu 22.04 base image `FROM mcr.microsoft.com/devcontainers/base:ubuntu-20.04`
- [x] install python 3.8
- [x] upgrade pip to the latest version
- [x] install latest version of pipenv
- [ ] [mount files from local filesystem](https://code.visualstudio.com/docs/devcontainers/containers#_quick-start-open-an-existing-folder-in-a-container)
- [ ] attach a python debugger to dev container and hit a breakpoint

Some investigation will be required as to where/when the dependencies will be installed. Since the

**Comment by faucomte97** [comment]
@SKairinos, I've just opened a PR for this, if you can test it on your machine to ensure at least that this attempt works. Then we can discuss the final details.

**Comment by faucomte97** [comment]
Gitbook docs review: https://app.gitbook.com/o/-M_6U74XVytl1uT1MyQy/s/-M_6UDUiGoJDhr_OXetO/~/changes/237/git/common-setup

**Comment by SKairinos** [comment]
@faucomte97, regarding the gitbook docs, you forgot to add the step of installing and setting up git. looks good otherwise
