### ISSUE TITLE
api auth backends

### ISSUE THREAD

**Issue by SKairinos** [ocadotechnology/codeforlife-workspace#92]
When the frontend calls our Django backend to log the user in, Django uses [authentication backends](https://docs.djangoproject.com/en/3.2/topics/auth/customizing/#writing-an-authentication-backend) to determine whether or not the user is logged in or can be logged in.

As an example, we currently have some custom authentication backends [here](https://github.com/ocadotechnology/codeforlife-package-python/blob/c0ce515a4e5557c757e19dc8aa15ebb0437bc887/codeforlife/user/auth/backends). These backends are then used in our [SSO service](https://github.com/ocadotechnology/codeforlife-portal-backend/tree/development/src/sso). You'll notice there is a login form for each auth backend. These login forms are then used in the login view. This login view is registered in the urls.

This task will require you to:
- [x] take the logic you wrote in your custom login_into_github action and refactor the code to work as an authentication backend.
- [x] create a form that has the correct fields for the auth backend (note that you will now need to call the login endpoint with HTTP POST, not HTTP GET, and supply the fields in the request body - use thunder client extension in vscode)
- [x] create the login view which calls the login form. This login view should return a session_metadata cookie which is http_only = False and has a JSON string containing the contributor's id.

**Comment by SalmanAsh** [comment]
`        # lookup_view can be URL name or callable, but callables are not
        # friendly in error messages.
        m = getattr(lookup_view, '__module__', None)
        n = getattr(lookup_view, '__name__', None)
        if m is not None and n is not None:
            lookup_view_s = "%s.%s" % (m, n)
        else:
            lookup_view_s = lookup_view
    
        patterns = [pattern for (_, pattern, _, _) in possibilities]
        if patterns:
            if args:
                arg_msg = "arguments '%s'" % (args,)
            elif kwargs:
                arg_msg = "keyword arguments '%s'" % kwargs
            else:
                arg_msg = "no arguments"
            msg = (
                "Reverse for '%s' with %s not found. %d pattern(s) tried: %s" %
                (lookup_view_s, arg_msg, len(patterns), patterns)
            )
        else:
            msg = (
                "Reverse for '%(view)s' not found. '%(view)s' is not "
                "a valid view function or pattern name." % {'view': lookup_view_s}
            )
>       raise NoReverseMatch(msg)
E       django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.

.venv/lib/python3.8/site-packages/django/urls/resolvers.py:698: NoReverseMatch`
